//! Auto-generates `register_all(ctx)` from `Cargo.toml` + active feature flags.
//!
//! Each sibling crate listed under `[dependencies]` (or under
//! `[target.'cfg(target_os = "macos")'.dependencies]`, gated
//! accordingly) gets a `crate::register(ctx)` call in `register_all`
//! **only if its corresponding cargo feature is enabled**
//! (`CARGO_FEATURE_<NAME>` env var). Consumers depending on us with
//! `default-features = false` and a custom feature subset get a slimmer
//! `register_all` body with only the crates they asked for.
//!
//! Feature name = crate short name (with hyphens preserved), with one
//! special case: `oxideav-mod` maps to feature `amiga-mod` (avoids
//! shadowing the `mod` Rust keyword in feature lists).
//!
//! The generated file is emitted to `$OUT_DIR/register_all.rs` and
//! pulled into `src/lib.rs` via `include!()`. Adding a sibling = add an
//! optional dep + a `name = ["dep:oxideav-name"]` feature line in
//! Cargo.toml; this script regenerates `register_all` on the next build.
//!
//! No linkme, no DCE concerns, no `#[used]` magic, no wasm caveats —
//! explicit fn calls force the linker to keep each rlib alive
//! naturally.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Crates we depend on but that should NOT be in `register_all`:
/// - `oxideav-core` is the foundation, not a register-emitting sibling.
const SKIP: &[&str] = &["oxideav-core"];

/// Special feature-name overrides for crates whose feature name doesn't
/// equal the crate short name. Currently just `oxideav-mod` →
/// `amiga-mod` (avoids the `mod` Rust keyword as a feature).
fn feature_name_for(crate_short: &str) -> String {
    match crate_short {
        "mod" => "amiga-mod".to_string(),
        other => other.to_string(),
    }
}

/// `CARGO_FEATURE_X` env var name for a feature. Cargo upcases the
/// feature name and replaces dashes with underscores.
fn env_var_for_feature(feat: &str) -> String {
    format!("CARGO_FEATURE_{}", feat.replace('-', "_").to_uppercase())
}

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest = fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let (general, mac_only) = collect_sibling_deps(&manifest);

    let mut out = String::new();
    out.push_str("// Auto-generated by build.rs from Cargo.toml + active feature flags. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// `register_all(ctx)` explicitly invokes every enabled sibling's\n");
    out.push_str("// `register(ctx)` fn. Each call forces the linker to keep the\n");
    out.push_str("// sibling rlib alive (no DCE concerns) — that's the point of\n");
    out.push_str("// using explicit calls instead of the linkme distributed-slice\n");
    out.push_str("// approach.\n\n");
    out.push_str("/// Walk every sibling crate enabled at build time and invoke its\n");
    out.push_str("/// `register(ctx)` fn. The call set is determined by which cargo\n");
    out.push_str("/// features are active when this crate is built; see Cargo.toml\n");
    out.push_str("/// for the audio/video/image/subtitle/hwaccel preset bundles +\n");
    out.push_str("/// per-crate features.\n");
    out.push_str("pub fn register_all(ctx: &mut oxideav_core::RuntimeContext) {\n");

    let mut emit = |crate_short: &str, mac_gate: bool| {
        let feature = feature_name_for(crate_short);
        let env_var = env_var_for_feature(&feature);
        if env::var_os(&env_var).is_none() {
            return; // feature off, skip
        }
        let krate = format!("oxideav_{}", crate_short.replace('-', "_"));
        if mac_gate {
            out.push_str("    #[cfg(target_os = \"macos\")]\n");
        }
        out.push_str(&format!("    {krate}::register(ctx);\n"));
    };

    // Strip "oxideav-" prefix for the per-feature env var lookup.
    for full_name in &general {
        let short = full_name.strip_prefix("oxideav-").unwrap_or(full_name);
        emit(short, false);
    }
    for full_name in &mac_only {
        let short = full_name.strip_prefix("oxideav-").unwrap_or(full_name);
        emit(short, true);
    }

    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("register_all.rs");
    fs::write(&dest, out).expect("write register_all.rs");
}

/// Parse `Cargo.toml` for `oxideav-*` deps in `[dependencies]` and in
/// `[target.'cfg(target_os = "macos")'.dependencies]`. Returns
/// `(general, mac_only)` in alphabetical order.
fn collect_sibling_deps(manifest: &str) -> (Vec<String>, Vec<String>) {
    #[derive(Clone, Copy, PartialEq)]
    enum Section {
        Skip,
        General,
        MacOnly,
    }

    let mut section = Section::Skip;
    let mut general = Vec::<String>::new();
    let mut mac_only = Vec::<String>::new();

    for line in manifest.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            let header: String = trimmed
                .trim_start_matches('[')
                .trim_end_matches(']')
                .chars()
                .filter(|c| !c.is_whitespace())
                .collect();
            section = if header == "dependencies" {
                Section::General
            } else if header == "target.'cfg(target_os=\"macos\")'.dependencies"
                || header == "target.\"cfg(target_os=\\\"macos\\\")\".dependencies"
            {
                Section::MacOnly
            } else {
                Section::Skip
            };
            continue;
        }

        if section == Section::Skip {
            continue;
        }
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let Some(eq) = trimmed.find('=') else {
            continue;
        };
        let key = trimmed[..eq].trim();
        if !key.starts_with("oxideav-") || SKIP.contains(&key) {
            continue;
        }
        let bucket = match section {
            Section::General => &mut general,
            Section::MacOnly => &mut mac_only,
            Section::Skip => unreachable!(),
        };
        bucket.push(key.to_string());
    }

    general.sort();
    mac_only.sort();
    (general, mac_only)
}
