//! Auto-generates `register_all(ctx)` from `Cargo.toml` + active feature flags.
//!
//! Each sibling crate listed under `[dependencies]` or under one of
//! the recognized `[target.'cfg(...)'.dependencies]` sections gets a
//! `crate::register(ctx)` call in `register_all` **only if its
//! corresponding cargo feature is enabled** (`CARGO_FEATURE_<NAME>`
//! env var). Consumers depending on us with `default-features = false`
//! and a custom feature subset get a slimmer `register_all` body with
//! only the crates they asked for.
//!
//! Recognized target gates (the `cfg(...)` body is emitted verbatim as
//! a `#[cfg(...)]` attribute on the generated `register` call so the
//! cross-target build still produces working code):
//!
//! - `target_os = "macos"`           — VideoToolbox / AudioToolbox
//! - `target_os = "linux"`            — VA-API / VDPAU / NVIDIA
//! - `any(target_os = "linux", target_os = "windows")` — Vulkan Video
//!
//! Feature name = crate short name (with hyphens preserved), with one
//! special case: `oxideav-mod` maps to feature `amiga-mod` (avoids
//! shadowing the `mod` Rust keyword in feature lists).
//!
//! The generated file is emitted to `$OUT_DIR/register_all.rs` and
//! pulled into `src/lib.rs` via `include!()`. Adding a sibling = add an
//! optional dep + a `name = ["dep:oxideav-name"]` feature line in
//! Cargo.toml; this script regenerates `register_all` on the next build.
//!
//! No linkme, no DCE concerns, no `#[used]` magic, no wasm caveats —
//! explicit fn calls force the linker to keep each rlib alive
//! naturally.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Crates we depend on but that should NOT be in `register_all`:
/// - `oxideav-core` is the foundation, not a register-emitting sibling.
/// - The 3D crates (`oxideav-mesh3d` + the four format siblings) use a
///   separate dispatch contract: they register into a
///   `oxideav_mesh3d::Mesh3DRegistry` via `populate_mesh3d_registry`,
///   not into the codec/container/filter/source RuntimeContext that
///   `register_all` walks.
const SKIP: &[&str] = &[
    "oxideav-core",
    "oxideav-mesh3d",
    "oxideav-stl",
    "oxideav-obj",
    "oxideav-gltf",
    "oxideav-usdz",
];

/// 3D format-codec crates. Each exposes `pub fn register(&mut
/// oxideav_mesh3d::Mesh3DRegistry)` (gated behind its default-on
/// `registry` feature). `populate_mesh3d_registry` calls each enabled
/// crate's `register` so a single helper builds a full registry.
const MESH3D_FORMAT_CRATES: &[&str] = &["stl", "obj", "gltf", "usdz", "fbx"];

/// Each section's parser key (the normalized `Cargo.toml` table
/// header with whitespace stripped) paired with the `cfg(...)` body
/// to emit on the generated `register` call. `None` body = the plain
/// `[dependencies]` section, no cfg attribute.
const SECTIONS: &[(&str, Option<&str>)] = &[
    ("dependencies", None),
    (
        "target.'cfg(target_os=\"macos\")'.dependencies",
        Some("target_os = \"macos\""),
    ),
    (
        "target.'cfg(target_os=\"linux\")'.dependencies",
        Some("target_os = \"linux\""),
    ),
    (
        "target.'cfg(any(target_os=\"linux\",target_os=\"windows\"))'.dependencies",
        Some("any(target_os = \"linux\", target_os = \"windows\")"),
    ),
];

/// Special feature-name overrides for crates whose feature name doesn't
/// equal the crate short name. Currently just `oxideav-mod` →
/// `amiga-mod` (avoids the `mod` Rust keyword as a feature).
fn feature_name_for(crate_short: &str) -> String {
    match crate_short {
        "mod" => "amiga-mod".to_string(),
        other => other.to_string(),
    }
}

/// `CARGO_FEATURE_X` env var name for a feature. Cargo upcases the
/// feature name and replaces dashes with underscores.
fn env_var_for_feature(feat: &str) -> String {
    format!("CARGO_FEATURE_{}", feat.replace('-', "_").to_uppercase())
}

fn main() {
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest = fs::read_to_string("Cargo.toml").expect("read Cargo.toml");
    let deps = collect_sibling_deps(&manifest);

    let mut out = String::new();
    out.push_str(
        "// Auto-generated by build.rs from Cargo.toml + active feature flags. Do not edit.\n",
    );
    out.push_str("//\n");
    out.push_str("// `register_all(ctx)` explicitly invokes every enabled sibling's\n");
    out.push_str("// `__oxideav_entry(ctx)` wrapper (generated by the\n");
    out.push_str("// `oxideav_core::register!` macro at the sibling's call site).\n");
    out.push_str("// Each call forces the linker to keep the sibling rlib alive\n");
    out.push_str("// (no DCE concerns).\n\n");
    out.push_str("/// Walk every sibling crate enabled at build time and invoke its\n");
    out.push_str("/// `__oxideav_entry(ctx)` wrapper. The call set is determined by which cargo\n");
    out.push_str("/// features are active when this crate is built; see Cargo.toml\n");
    out.push_str("/// for the audio/video/image/subtitle/hwaccel preset bundles +\n");
    out.push_str("/// per-crate features.\n");
    out.push_str("pub fn register_all(ctx: &mut oxideav_core::RuntimeContext) {\n");
    // Silence `unused_variables` when no register-emitting feature is
    // enabled (e.g. `--features 3d` builds where every dep is in SKIP).
    out.push_str("    let _ = ctx;\n");

    for (full_name, gate) in &deps {
        let short = full_name.strip_prefix("oxideav-").unwrap_or(full_name);
        let feature = feature_name_for(short);
        let env_var = env_var_for_feature(&feature);
        if env::var_os(&env_var).is_none() {
            continue; // feature off, skip
        }
        let krate = format!("oxideav_{}", short.replace('-', "_"));
        if let Some(g) = gate {
            out.push_str(&format!("    #[cfg({g})]\n"));
        }
        out.push_str(&format!("    {krate}::__oxideav_entry(ctx);\n"));
    }

    out.push_str("}\n");

    // Second generated function: `populate_mesh3d_registry`. Lives
    // behind `#[cfg(feature = "mesh3d")]` so `oxideav_mesh3d` is in
    // scope. Each enabled 3D-format crate's `register(&mut
    // Mesh3DRegistry)` is called in turn (gated on its own feature).
    out.push('\n');
    out.push_str("/// Populate a [`oxideav_mesh3d::Mesh3DRegistry`] with every enabled\n");
    out.push_str("/// 3D-format codec sibling's decoder + encoder factories.\n");
    out.push_str("///\n");
    out.push_str("/// Parallel to [`register_all`] but for the separate Mesh3DRegistry\n");
    out.push_str("/// dispatch contract that 3D-format crates use. Only available when\n");
    out.push_str("/// the `mesh3d` cargo feature is enabled (i.e. when `oxideav-mesh3d`\n");
    out.push_str("/// is in the dep tree).\n");
    out.push_str("#[cfg(feature = \"mesh3d\")]\n");
    out.push_str(
        "pub fn populate_mesh3d_registry(registry: &mut oxideav_mesh3d::Mesh3DRegistry) {\n",
    );
    // Silence `unused_variables` when only `mesh3d` is on (no format
    // codecs enabled) — registry stays empty but compiles cleanly.
    out.push_str("    let _ = registry;\n");
    for short in MESH3D_FORMAT_CRATES {
        let env_var = env_var_for_feature(short);
        if env::var_os(&env_var).is_none() {
            continue;
        }
        let krate = format!("oxideav_{}", short.replace('-', "_"));
        out.push_str(&format!("    {krate}::register(registry);\n"));
    }
    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR set by cargo"));
    let dest = out_dir.join("register_all.rs");
    fs::write(&dest, out).expect("write register_all.rs");
}

/// Parse `Cargo.toml` for `oxideav-*` deps in any of the recognized
/// `SECTIONS` headers. Returns `Vec<(crate_name, cfg_gate)>` where
/// `cfg_gate = None` means the dep was in `[dependencies]` (no
/// `#[cfg]` attribute on the generated call) and `Some(s)` means
/// emit `#[cfg(s)]` on the call.
///
/// Output is sorted: `None` gates first (so the `[dependencies]`
/// crates emit before the target-gated ones), then by gate string,
/// then by crate name. Deterministic across runs.
fn collect_sibling_deps(manifest: &str) -> Vec<(String, Option<String>)> {
    let mut deps: Vec<(String, Option<String>)> = Vec::new();
    let mut active: Option<Option<&'static str>> = None;

    for line in manifest.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            let header: String = trimmed
                .trim_start_matches('[')
                .trim_end_matches(']')
                .chars()
                .filter(|c| !c.is_whitespace())
                .collect();
            active = SECTIONS
                .iter()
                .find(|(key, _)| *key == header)
                .map(|(_, gate)| *gate);
            continue;
        }

        let Some(gate) = active else {
            continue;
        };
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        let Some(eq) = trimmed.find('=') else {
            continue;
        };
        let key = trimmed[..eq].trim();
        if !key.starts_with("oxideav-") || SKIP.contains(&key) {
            continue;
        }
        deps.push((key.to_string(), gate.map(|s| s.to_string())));
    }

    deps.sort();
    deps
}
