//! Aggregator crate: explicit `register_all(ctx)` over every enabled
//! sibling codec / container / filter / source crate.
//!
//! Replaces the old `oxideav-format-all` + linkme distributed-slice
//! approach. Why explicit calls instead of linkme:
//!
//! - **Wasm support**: linkme's distributed-slice mechanism has open
//!   issues on `wasm32-*` targets. Explicit fn calls work everywhere
//!   Rust does.
//! - **No DCE concerns**: explicit `oxideav_aac::register(ctx)` calls
//!   force the linker to keep each rlib alive — the `ensure_linked()`
//!   workaround the slice approach needed is gone.
//! - **No `#[used]` magic, no ctor / init_array tricks** — just
//!   straightforward function calls.
//!
//! # Quick start
//!
//! ```toml
//! [dependencies]
//! oxideav-core = "0.1"
//! oxideav-meta = "*"
//! ```
//!
//! ```ignore
//! use oxideav_core::RuntimeContext;
//!
//! let mut ctx = RuntimeContext::new();
//! oxideav_meta::register_all(&mut ctx);
//! // ctx now has every codec / container / filter / source enabled at
//! // build time (default-features = ["all"] turns on everything).
//! ```
//!
//! # Slimming the build
//!
//! Default-features pulls every sibling. Opt down to a subset by
//! turning off defaults and picking your own:
//!
//! ```toml
//! [dependencies]
//! # Just image codecs.
//! oxideav-meta = { version = "*", default-features = false, features = ["image"] }
//!
//! # Just MP4 + H.264 + AAC.
//! oxideav-meta = { version = "*", default-features = false, features = ["mp4", "h264", "aac"] }
//! ```
//!
//! Preset bundles available: `audio`, `video`, `image`, `subtitles`,
//! `hwaccel`, `source-drivers`, `all`, `pure-rust` (= `all` minus
//! `hwaccel`, for builds that want zero FFI to OS HW-engine APIs).
//! Per-crate features named after each crate's short name (`aac`,
//! `h264`, `mp4`, …; one exception: `oxideav-mod` is feature
//! `amiga-mod` to avoid the `mod` keyword).

// `register_all(ctx)` fn — auto-generated by `build.rs` from Cargo.toml
// + active feature flags.
include!(concat!(env!("OUT_DIR"), "/register_all.rs"));
