//! Aggregator crate: explicit `register_all(ctx)` over every enabled
//! sibling codec / container / filter / source crate.
//!
//! Replaces the old `oxideav-format-all` + linkme distributed-slice
//! approach. Why explicit calls instead of linkme:
//!
//! - **Wasm support**: linkme's distributed-slice mechanism has open
//!   issues on `wasm32-*` targets. Explicit fn calls work everywhere
//!   Rust does.
//! - **No DCE concerns**: explicit `oxideav_aac::register(ctx)` calls
//!   force the linker to keep each rlib alive — the `ensure_linked()`
//!   workaround the slice approach needed is gone.
//! - **No `#[used]` magic, no ctor / init_array tricks** — just
//!   straightforward function calls.
//!
//! # Quick start
//!
//! ```toml
//! [dependencies]
//! oxideav-core = "0.1"
//! oxideav-meta = "*"
//! ```
//!
//! ```ignore
//! use oxideav_core::RuntimeContext;
//!
//! let mut ctx = RuntimeContext::new();
//! oxideav_meta::register_all(&mut ctx);
//! // ctx now has every codec / container / filter / source enabled at
//! // build time (default-features = ["all"] turns on everything).
//! ```
//!
//! # Slimming the build
//!
//! Default-features pulls every sibling. Opt down to a subset by
//! turning off defaults and picking your own:
//!
//! ```toml
//! [dependencies]
//! # Just image codecs.
//! oxideav-meta = { version = "*", default-features = false, features = ["image"] }
//!
//! # Just MP4 + H.264 + AAC.
//! oxideav-meta = { version = "*", default-features = false, features = ["mp4", "h264", "aac"] }
//! ```
//!
//! Preset bundles available: `audio`, `video`, `image`, `subtitles`,
//! `3d`, `hwaccel`, `source-drivers`, `all`, `pure-rust` (= `all` minus
//! `hwaccel`, for builds that want zero FFI to OS HW-engine APIs).
//! Per-crate features named after each crate's short name (`aac`,
//! `h264`, `mp4`, …; one exception: `oxideav-mod` is feature
//! `amiga-mod` to avoid the `mod` keyword).
//!
//! # 3D scenes & assets
//!
//! The `3d` preset enables `oxideav-mesh3d` (typed Scene3D / Mesh /
//! Material / Animation model + `Mesh3DRegistry`) plus the four format
//! codec siblings (`oxideav-stl`, `oxideav-obj`, `oxideav-gltf`,
//! `oxideav-usdz`). They use a separate dispatch contract from the
//! codec/container/filter/source path that [`register_all`] walks —
//! call [`populate_mesh3d_registry`] to wire them into a registry:
//!
//! ```ignore
//! # #[cfg(feature = "mesh3d")] {
//! use oxideav_mesh3d::Mesh3DRegistry;
//!
//! let mut reg = Mesh3DRegistry::new();
//! oxideav_meta::populate_mesh3d_registry(&mut reg);
//! // reg now resolves stl/obj/gltf/usdz by extension or format-id.
//! # }
//! ```
//!
//! # 3D rendering
//!
//! The `3d` preset also enables `oxideav-render` (Scene3D → packed
//! RGBA8 via the in-tree scanline backend, with raycaster + path-tracer
//! backends planned). Like [`populate_mesh3d_registry`], the renderer
//! uses a separate `RenderRegistry` dispatch contract — call
//! [`populate_render_registry`] to wire every enabled backend into a
//! registry:
//!
//! ```ignore
//! # #[cfg(feature = "render")] {
//! use oxideav_render::RenderRegistry;
//!
//! let mut reg = RenderRegistry::new();
//! oxideav_meta::populate_render_registry(&mut reg);
//! // reg now resolves "scanline" (and future raycaster / path-tracer
//! // backends as they land).
//! # }
//! ```

// `register_all(ctx)` fn — auto-generated by `build.rs` from Cargo.toml
// + active feature flags.
include!(concat!(env!("OUT_DIR"), "/register_all.rs"));
